// Import necessary dependencies
import React from 'react';
import styled from 'styled-components';

// Styled components for your About page
const AboutContainer = styled.div`
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
`;

const Title = styled.h1`
  color: #333;
  font-size: 2em;
`;

const Paragraph = styled.p`
  color: #666;
  font-size: 1.2em;
  line-height: 1.5;
`;

// About page component
const AboutPage = () => {
  return (
    <AboutContainer>
      <Title>About DDoS Analyser</Title>
      <Paragraph>
        This application is designed to analyze logs generated by applications for detecting DDoS attacks. It gathers real-time traffic data, logs it, analyzes it, and generates graphs to determine if an attack has occurred.
      </Paragraph>
      <Paragraph>
        We have used various machine learning and data analysis libraries such as pandas, seaborn, numpy, matplotlib, and sklearn to process and analyze the data. The application uses different classifiers like BaggingClassifier, GradientBoostingClassifier, AdaBoostClassifier, RandomForestClassifier, and DecisionTreeClassifier for the detection of DDoS attacks.
      </Paragraph>
      <Paragraph>
        The application also uses metrics like accuracy score, log loss, ROC curve, AUC, precision recall curve, and others to evaluate the performance of the classifiers.
      </Paragraph>
      <Paragraph>
        The data is preprocessed using LabelEncoder, StandardScaler, and SimpleImputer from sklearn.preprocessing. We also use PCA for dimensionality reduction.
      </Paragraph>
      <Paragraph>
        The application is designed with a user-friendly interface that allows users to easily navigate and understand the results of the analysis.
      </Paragraph>
    </AboutContainer>
  );
};

export default AboutPage;
